spring.datasource.url=jdbc:sqlserver://soc3-ng.abis.be;database=training;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=tu00030
spring.datasource.password=tu00030